services:
  kafka:
    image: apache/kafka:4.1.1
    ports:
      - "9092:9092"
    environment:
      # ID único para el cluster (Obligatorio en la imagen oficial para iniciar KRaft)
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
      # Configuración de roles y puertos
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # Optimizaciones para entorno local (1 solo nodo)
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025" # Interfaz Web: Accede a http://localhost:8025 para ver tus correos
      - "1025:1025" # Puerto SMTP: Donde Spring Boot enviará los correos

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379" # Puerto estándar de Redis
    volumes:
      - redis_data:/data # Guarda los datos en disco para no perder las sesiones al reiniciar
    restart: unless-stopped # Se reiniciará automáticamente si falla o si reinicias Docker

# Declaración de los volúmenes persistentes
volumes:
  redis_data: