spring.application.name=pibblest
# Le dice a Spring el nombre base de tus archivos (messages.properties)
spring.messages.basename=messages

# Obliga a leer los archivos en UTF-8 para soportar acentos de forma nativa
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

spring.datasource.url=${PIBBLEST_DB_URL}
spring.datasource.username=${PIBBLEST_DB_USER}
spring.datasource.password=${PIBBLEST_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/api/swagger-ui