server.port=8081
spring.application.name=pibblest
# Le dice a Spring el nombre base de tus archivos (messages.properties)
spring.messages.basename=messages

# Obliga a leer los archivos en UTF-8 para soportar acentos de forma nativa
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

spring.datasource.url=${PIBBLEST_DB_URL}
spring.datasource.username=${PIBBLEST_DB_USER}
spring.datasource.password=${PIBBLEST_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/api/swagger-ui


spring.kafka.bootstrap-servers=localhost:9092

# 2. KAFKA PRODUCER (El que envía)
# ==========================================
# Modulith entrega bytes, así que usamos ByteArraySerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# ==========================================
# 3. KAFKA CONSUMER (El que recibe)
# ==========================================
# Le decimos a Kafka que simplemente reciba los bytes y se los pase a Spring
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer


#spring.kafka.consumer.properties.spring.json.trusted.packages=java.util,java.lang,com.nss.pibblest.*

#spring.kafka.consumer.properties.spring.json.ignore.unknown.properties=true



#modulith
# Reemplaza "esquema_eventos" por el nombre real de tu esquema
spring.modulith.events.jdbc.schema=events


# Configuración del servidor SMTP local (Mailpit)
spring.mail.host=localhost
spring.mail.port=1025
# Mailpit no requiere autenticación ni TLS por defecto
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

## Feature (Send emails to registered owners)
frontend.url=http://localhost:3000

#jwt
security.jwt.secret-key=${SECRET_KEY}
security.jwt.expiration-time=${EXP_TIME}


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true

#redis

spring.data.redis.host=localhost
spring.data.redis.port=6379


#app.runners.script-migracion=true
app.email=hola@example.com

time.to.wait.resend.token=1