spring.application.name=pibblest

spring.datasource.url=${PIBBLEST_DB_URL}
spring.datasource.username=${PIBBLEST_DB_USER}
spring.datasource.password=${PIBBLEST_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/api/swagger-ui